Repository moit03/moit-be, pull requests merged in 2024-04, with the labels that each got.

#26 [Feat] 기술스택, 경력 필터 구현 + 슬랙 연동
  .github/workflows/slack-notification.yml
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: feature

#27 [FEAT] 모임 참가 기능
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java
  src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingRequestDto.java
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/entity/MeetingMember.java
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting_Member.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/entity/Member.java
  src/main/java/com/sparta/moit/global/error/ErrorCode.java
  src/main/java/com/sparta/moit/global/security/UserDetailsServiceImpl.java
Labels: feature

#28 [Feat] 지역별 모임 조회 기능 구현
  build.gradle
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/global/common/controller/CommonController.java
  src/main/java/com/sparta/moit/global/common/dto/AddressResponseDto.java
  src/main/java/com/sparta/moit/global/util/AddressUtil.java
  src/main/java/com/sparta/moit/global/util/UtilExam.java
Labels: feature

#30 [FEAT] 모임 삭제 기능
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: feature

#36 Moitbe 74 feat/mypage/information
  src/main/java/com/sparta/moit/domain/meeting/dto/GetMyPageDto.java
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/member/controller/MemberController.java
  src/main/java/com/sparta/moit/domain/member/entity/Member.java
  src/main/java/com/sparta/moit/domain/member/service/KakaoService.java
  src/main/java/com/sparta/moit/domain/mypage/contoller/MypageController.java
  src/main/java/com/sparta/moit/domain/mypage/contoller/MypageControllerDocs.java
  src/main/java/com/sparta/moit/domain/mypage/dto/MypageResponseDto.java
  src/main/java/com/sparta/moit/domain/mypage/service/MypageService.java
  src/main/java/com/sparta/moit/domain/mypage/service/MypageServiceImpl.java
  src/main/java/com/sparta/moit/global/error/ErrorCode.java
Labels: feature

#38 [FEAT] 모임 탈퇴 기능
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/repository/MemberRepository.java
  src/main/java/com/sparta/moit/domain/mypage/service/MypageServiceImpl.java
Labels: feature

#43 [FIX] 모임 탈퇴 기능
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: fix

#47 [FIX]모임 삭제 기능
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/entity/MeetingMember.java
  src/main/java/com/sparta/moit/domain/meeting/entity/MeetingStatusEnum.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/entity/Member.java
Labels: fix

#49 [FIX] 모임 상태 추가
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: fix

#51 [FIX] 모임 상태 추가
  src/main/java/com/sparta/moit/MoitApplication.java
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/meeting/scheduler/Scheduler.java
Labels: fix

#52 [Feat] MeetingDetail 로그인 분기 + 참여 여부 로직 추가
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java
  src/main/java/com/sparta/moit/domain/meeting/dto/GetMeetingDetailResponseDto.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: feature

#56 [Feat] 무한 스크롤 api 구현
  src/main/java/com/sparta/moit/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/moit/domain/chat/controller/docs/ChatControllerDocs.java
  src/main/java/com/sparta/moit/domain/chat/dto/ChatResponseDto.java
  src/main/java/com/sparta/moit/domain/chat/dto/SingleChatResponseDto.java
  src/main/java/com/sparta/moit/domain/chat/repository/ChatRepository.java
  src/main/java/com/sparta/moit/domain/chat/service/ChatService.java
  src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java
Labels: feature

#65 [FIX] 모임 수정, 조회
  build.gradle
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingRequestDto.java
  src/main/java/com/sparta/moit/domain/meeting/dto/MeetingFilterCondition.java
  src/main/java/com/sparta/moit/domain/meeting/dto/MeetingRequestDto.java
  src/main/java/com/sparta/moit/domain/meeting/dto/UpdateMeetingRequestDto.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingCareerRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingSkillRepository.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/KakaoServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/NaverServiceImpl.java
  src/main/java/com/sparta/moit/global/common/controller/AuthController.java
  src/main/java/com/sparta/moit/global/common/repository/RedisRefreshTokenRepository.java
  src/main/java/com/sparta/moit/global/common/service/RedisService.java
  src/main/java/com/sparta/moit/global/common/service/RefreshTokenService.java
  src/main/java/com/sparta/moit/global/jwt/JwtUtil.java
  src/main/java/com/sparta/moit/global/service/TestService.java
  src/main/java/com/sparta/moit/infra/InfraExam.java
  src/main/resources/application.properties
  src/test/java/com/sparta/moit/NaverServiceTest.java
  src/test/java/com/sparta/moit/domain/meeting/controller/MeetingControllerTest.java
  src/test/java/com/sparta/moit/domain/meeting/service/MeetingServiceImplTest.java
Labels: fix

#67 [FIX] 코드 리뷰 반영
  src/main/java/com/sparta/moit/MoitApplication.java
  src/main/java/com/sparta/moit/domain/chat/controller/ChatController.java
  src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/entity/Meeting.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/controller/MemberController.java
  src/main/java/com/sparta/moit/domain/mypage/controller/MypageController.java
  src/main/java/com/sparta/moit/domain/mypage/controller/docs/MypageControllerDocs.java
  src/main/java/com/sparta/moit/domain/mypage/service/MypageServiceImpl.java
  src/main/resources/application.properties
Labels: fix

#69 Moitbe 105 feat/mypagefix
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/mypage/service/MypageServiceImpl.java
  src/main/java/com/sparta/moit/global/config/RedisConfig.java
Labels: fix

#76 [ETC] Prometheus설정
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/com/sparta/moit/global/config/WebSecurityConfig.java
  src/main/resources/application.properties
Labels: monitoring

#89 [fix] creatAT, ModifyAt -> KST 수정
  elasticbeanstalk/docker-compose.yml
  src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingResponseDto.java
Labels: fix

#110 [Feat] Popular meeting API, deleted meeting exception
  src/main/java/com/sparta/moit/domain/meeting/controller/MeetingController.java
  src/main/java/com/sparta/moit/domain/meeting/dto/GetPopularResponseDto.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingService.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: feature

#113 fix] zoneDate -> LocalDateTime
  src/main/java/com/sparta/moit/domain/meeting/dto/CreateMeetingRequestDto.java
  src/main/java/com/sparta/moit/domain/member/controller/MemberController.java
  src/main/java/com/sparta/moit/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/sparta/moit/domain/member/service/KakaoServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/MemberService.java
  src/main/java/com/sparta/moit/domain/member/service/MemberServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/NaverServiceImpl.java
Labels: fix

#114 [Fix] 인기모임 날짜 수정 + 삭제, 완료된 모임 채팅 금지
  src/main/java/com/sparta/moit/domain/chat/service/ChatServiceImpl.java
  src/main/java/com/sparta/moit/domain/meeting/controller/docs/MeetingControllerDocs.java
  src/main/java/com/sparta/moit/domain/meeting/dto/GetPopularResponseDto.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/global/common/controller/CommonController.java
Labels: fix

#117 [fix] 상세페이지 bookmark 여부 수정
  src/main/java/com/sparta/moit/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
Labels: fix

#123 Moitbe 115 fix/meeting
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/global/util/pagination/ListPaginator.java
Labels: fix

#124 [Fix] MyPage OrderBy 추가 + Docker-compose 자바 시간 UTC
  elasticbeanstalk/docker-compose.yml
  src/main/java/com/sparta/moit/domain/bookmark/repository/BookMarkRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryCustom.java
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
Labels: fix

#131 [FEAT] 회원 탈퇴 기능
  .gitignore
  src/main/java/com/sparta/moit/domain/member/controller/MemberController.java
  src/main/java/com/sparta/moit/domain/member/controller/docs/MemberControllerDocs.java
  src/main/java/com/sparta/moit/domain/member/entity/Member.java
  src/main/java/com/sparta/moit/domain/member/entity/MemberStatusEnum.java
  src/main/java/com/sparta/moit/domain/member/service/KakaoServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/MemberService.java
  src/main/java/com/sparta/moit/domain/member/service/MemberServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/NaverServiceImpl.java
Labels: feature

#136 [Fix] 위도 경도 DB 수정 및 orderBy 추가
  src/main/java/com/sparta/moit/domain/meeting/repository/MeetingRepositoryImpl.java
  src/main/java/com/sparta/moit/domain/meeting/repository/RegionSecondRepository.java
  src/main/java/com/sparta/moit/domain/meeting/service/RegionServiceImpl.java
Labels: fix

#139 [Feat] 카카오 탈퇴 확인
  src/main/java/com/sparta/moit/domain/member/service/KakaoService.java
  src/main/java/com/sparta/moit/domain/member/service/KakaoServiceImpl.java
  src/main/java/com/sparta/moit/domain/member/service/MemberServiceImpl.java
  src/main/java/com/sparta/moit/global/error/ErrorCode.java
Labels: feature

#140 [FIX] 모임 수정 기능
  .gitignore
  src/main/java/com/sparta/moit/domain/meeting/service/MeetingServiceImpl.java
  src/main/java/com/sparta/moit/global/error/ErrorCode.java
Labels: fix
